# Generated by Django 4.1.7 on 2023-03-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.CharField(choices=[('Еда', 'Еда'), ('Машина', 'Машина'), ('Гаджеты', 'Гаджеты')], max_length=10, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='webapp', verbose_name='Картинка')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Отзыв')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_products', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_authors', to='webapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': ('Отзыв',),
                'verbose_name_plural': 'Отзыв',
            },
        ),
    ]
